@startuml
left to right direction
usecase uc as "**Sacar dinero**
--
+solicitud hecha"

usecase uc2 as "**Retener tarjeta**

"

skinparam usecase{
BackgroundColor Seagreen
BorderColor green
ArrowColor green
}

note "Description \n -- \n condición: \n  { historia sospechos } \n punto de extensión: \n  solicitud hecha " as des

 (uc) <.. des : <<Extend>>
 des .. (uc2)

@enduml